package org.pureagave.zodiac.control.data.discovery

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertTrue
import org.junit.Test
import org.pureagave.zodiac.control.core.geo.GoldenSpike
import org.pureagave.zodiac.control.core.ops.StreetRingRadiiM
import java.io.File
import kotlin.math.abs
import kotlin.math.hypot

/**
 * Ground-truth checks against the **shipped** offline seed asset
 * (`assets/brc/<ACTIVE_YEAR>/discovery_seed.json`) — the artifact a never-fetched
 * device boots from. It is generated by pulling a real device's own cache, so
 * these assert properties of production output, not of a hand-written fixture:
 *
 *  - it parses and carries the full dataset (a truncated/empty reship is caught);
 *  - its camp placement rate has not regressed to the 56%-drop bug the seed was
 *    born alongside — the whole reason the fix that produced it exists;
 *  - every placed camp sits on a real lettered ring, so a corrupted point, or a
 *    seed generated against different ring radii, is caught;
 *  - nothing placed escapes the 5 km plausibility gate.
 *
 * Mirrors [org.pureagave.zodiac.control.data.playa.BundledGisTest]'s discipline of
 * testing the bytes we actually ship, not a re-derivation of them.
 */
class DiscoverySeedAssetTest {
    private val records: List<JSONObject> by lazy {
        val arr = JSONArray(seedFile().readText())
        (0 until arr.length()).map { arr.getJSONObject(it) }
    }

    @Test
    fun the_seed_parses_and_carries_the_full_dataset() {
        // A wide floor: the 2026 feed shipped 1521 records. A near-empty or
        // truncated reship (a broken export) drops well below this.
        assertTrue("seed record count = ${records.size}", records.size > MIN_RECORDS)
    }

    @Test
    fun the_camp_placement_rate_has_not_regressed_to_the_56pct_drop() {
        val camps = records.filter { it.optString("kind") == "CAMP" }
        val placed = camps.count { it.has("eastM") }
        val rate = placed.toDouble() / camps.size
        // The bug placed 375/1190 = 0.32; the fix placed 1075/1190 = 0.90. A
        // floor of 0.80 sits in the wide gap between them, so only a regression
        // of the order-robustness fix (or a reship off a broken build) trips it.
        assertTrue("camp placement rate = $rate ($placed/${camps.size})", rate >= MIN_CAMP_PLACE_RATE)
    }

    @Test
    fun every_placed_camp_sits_on_a_real_lettered_ring() {
        val camps = records.filter { it.optString("kind") == "CAMP" && it.has("eastM") }
        assertTrue("placed camps = ${camps.size}", camps.size > MIN_PLACED_CAMPS)
        camps.forEach { o ->
            val r = radiusOf(o)
            assertTrue(
                "camp '${o.optString("name")}' at ${"%.1f".format(r)} m is off every lettered ring",
                onSomeRing(r),
            )
        }
    }

    @Test
    fun no_placed_record_escapes_the_five_km_plausibility_gate() {
        records.filter { it.has("eastM") }.forEach { o ->
            val r = radiusOf(o)
            assertTrue("'${o.optString("name")}' placed at ${"%.0f".format(r)} m is past the 5 km gate", r <= MAX_RADIUS_M)
        }
    }

    private fun radiusOf(o: JSONObject): Double = hypot(o.getDouble("eastM"), o.getDouble("northM"))

    private fun onSomeRing(radius: Double): Boolean = StreetRingRadiiM.values.any { abs(it - radius) <= RING_TOLERANCE_M }

    private companion object {
        const val MIN_RECORDS = 1_400
        const val MIN_PLACED_CAMPS = 900
        const val MIN_CAMP_PLACE_RATE = 0.80
        const val RING_TOLERANCE_M = 1.0
        const val MAX_RADIUS_M = 5_000.0

        /**
         * Unit tests run with the module dir as CWD under AGP, but don't rely on
         * it — walk up until the shipped assets tree appears, as BundledGisTest does.
         */
        fun seedFile(): File {
            var dir: File? = File("").absoluteFile
            while (dir != null) {
                val candidate = File(dir, "app/src/main/assets/brc/${GoldenSpike.ACTIVE_YEAR}/discovery_seed.json")
                if (candidate.isFile) return candidate
                val here = File(dir, "src/main/assets/brc/${GoldenSpike.ACTIVE_YEAR}/discovery_seed.json")
                if (here.isFile) return here
                dir = dir.parentFile
            }
            error("bundled discovery seed not found for ${GoldenSpike.ACTIVE_YEAR}")
        }
    }
}
