#!/usr/bin/env python3
"""Generate ``protocol/coverage-protocol-golden.json`` — the cross-language
golden corpus for the ZCOVER camera-coverage wire format (RES-P2-1).

Like the ZTHREAT corpus, every vector here is **measured, not authored**: the
fixed inputs below are run through this repo's own :mod:`zvision.coverage_protocol`
and whatever it actually produces is written down. Both suites
(``jetson/tests/test_coverage_golden.py`` and the tablet's
``CoverageProtocolGoldenTest.kt``) then read the file and must agree, so the
Python producer and the Kotlin consumer cannot silently drift.

Run from the repo root (or anywhere — paths are anchored to this file)::

    python3 jetson/tools/gen_coverage_golden.py

Do NOT hand-edit the JSON it writes: that lets you record what you *believe*
instead of what the code *does*, which is the whole failure this corpus exists
to prevent. Change the format, then re-run this tool.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# tools/this.py -> tools -> jetson -> repo root; make zvision importable.
_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_ROOT / "jetson"))

from zvision.coverage_protocol import (  # noqa: E402
    HEADER,
    MAX_ABS_START_DEG,
    MAX_ARCS,
    format_coverage,
    parse_coverage,
)
from zvision.threat_protocol import _NUMBER_PATTERN  # noqa: E402

_CORPUS = _ROOT / "protocol" / "coverage-protocol-golden.json"

# Lines fed to parse_coverage. Each becomes a parse vector recording exactly
# what this implementation returns (arcs, or None for a non-ZCOVER line).
_PARSE_INPUTS = [
    ("bare_header_all_blind", "ZCOVER"),
    ("single_forward_arc", "ZCOVER;-64.0:64.0"),
    ("two_disjoint_arcs", "ZCOVER;-30.0:30.0;100.0:170.0"),
    ("seam_crossing_arc_end_past_180", "ZCOVER;120.0:200.0"),
    ("whole_ring_covered", "ZCOVER;-180.0:180.0"),
    ("f32_rounded_values", "ZCOVER;12.34:56.78"),
    ("trailing_crlf_is_framing_only", "ZCOVER;-64.0:64.0\r\n"),
    ("not_a_coverage_line_is_rejected", "ZTHREAT;1:-12.0:0.300:0"),
    ("garbage_is_rejected", "HELLO WORLD"),
    ("empty_line_is_rejected", ""),
    ("malformed_arc_skipped_wellformed_kept", "ZCOVER;xx:yy;10.0:50.0"),
    ("hex_float_start_skipped", "ZCOVER;0x1p3:64.0"),
    ("start_out_of_range_skipped", "ZCOVER;200.0:250.0"),
    ("reversed_arc_skipped", "ZCOVER;50.0:10.0"),
    ("too_wide_arc_skipped", "ZCOVER;-180.0:200.0"),
    ("wrong_field_count_skipped", "ZCOVER;10.0:20.0:30.0;40.0:80.0"),
]

# Arc lists fed to format_coverage. Values are chosen exactly representable so
# both a 64-bit producer and a 32-bit consumer spell them identically — no
# precision-limit cases are needed for a 1-decimal degree field.
_FORMAT_INPUTS = [
    ("empty_is_all_blind", []),
    ("single_forward_arc", [[-64.0, 64.0]]),
    ("two_disjoint_arcs", [[-30.0, 30.0], [100.0, 170.0]]),
    ("seam_crossing_arc", [[120.0, 200.0]]),
    ("whole_ring", [[-180.0, 180.0]]),
    ("half_even_rounding", [[12.25, 45.75]]),
]


def _arc_list(arcs):
    return [[start, end] for start, end in arcs]


def build_corpus() -> dict:
    parse_vectors = []
    for name, frame in _PARSE_INPUTS:
        result = parse_coverage(frame)
        parse_vectors.append(
            {
                "name": name,
                "frame": frame,
                "expect": None if result is None else _arc_list(result),
            }
        )

    format_vectors = []
    for name, arcs in _FORMAT_INPUTS:
        format_vectors.append(
            {
                "name": name,
                "arcs": [list(a) for a in arcs],
                "frame": format_coverage([tuple(a) for a in arcs]),
            }
        )

    return {
        "_comment": [
            "GOLDEN CORPUS for the ZCOVER camera-coverage wire format (RES-P2-1)",
            "— the shared truth for two hand-written implementations:",
            "  producer  jetson/zvision/coverage_protocol.py   (Python, edge box)",
            "  consumer  app/.../core/vision/CoverageProtocol.kt (Kotlin, tablets)",
            "Both test suites read THIS FILE and fail loudly if it is missing.",
            "GENERATED by jetson/tools/gen_coverage_golden.py — do NOT hand-edit;",
            "change the format and re-run the tool (see protocol/README.md).",
            "parse_vectors:  frame -> covered arcs [[start,end],...], or",
            "                expect=null when the line is not a ZCOVER frame.",
            "                A bare 'ZCOVER' -> [] means nothing covered = all blind.",
            "format_vectors: covered arcs -> the exact bytes.",
        ],
        "header": HEADER,
        "max_arcs": MAX_ARCS,
        "max_abs_start_deg": MAX_ABS_START_DEG,
        "cover_decimals": 1,
        "number_grammar": _NUMBER_PATTERN.pattern,
        "parse_vectors": parse_vectors,
        "format_vectors": format_vectors,
    }


def main() -> int:
    corpus = build_corpus()
    _CORPUS.write_text(json.dumps(corpus, indent=1) + "\n")
    print(
        f"wrote {_CORPUS} — {len(corpus['parse_vectors'])} parse, "
        f"{len(corpus['format_vectors'])} format vectors"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
